# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75c87ef80efd952e2fee6bc91672008bc7f16a0670a1d5c3941f46d8e8f0de7ce0ee602c0f4e5f9880cfc43b93e080ffcde4b2b7fd82f939678f4c40e81baf16

test:
  secret_key_base: 7bdb0b934e235941e78f7f6b164bd021bfdd05996fc5127b948d207406da39f3287f09358546ce7c34ee61c867ec05a3a3343e17fa217637e409794f0a3f4971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
